### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by zuurw** [eduardorasgado/Robotics-ColumbiaX-Project3#1]
Hi, @eduardorasgado  I'd like to collaborate on this open source project and propose free logo/icon design for this project. If it's something you're interested in, please, let me know!
It´s great to work with you!
Best Regards
Zuur

**Comment by eduardorasgado** [comment]
You're welcome @zuurw, this project is all about the 7 DOF KUKA arm control, basically is a third party software for the movements control of industrial robot arms. Any idea about the logo? I think something simple like a gripper, the name could be: kinematica. Thanks for your contributions, it is a pleasure bro! Best regards!

**Comment by zuurw** [comment]
Hi @eduardorasgado, here is my design for this project, I enjoy a lot making this logo and I think it looks really good :)

The logo has great versions in black and white.

I hope you like it, I will wait for you feedback.

Best Regards!

![final proposal](https://user-images.githubusercontent.com/40801473/43214384-f747eecc-9030-11e8-90c0-aa9ea60334e1.png)

**Comment by eduardorasgado** [comment]
Damn bro! I really like this one. One design and the perfect one. Send me the PR mate! Well done :1st_place_medal:

**Comment by zuurw** [comment]
Hi @eduardorasgado, Im happy that you like it, I think this is my best logo design :) I love it!

I create the pull request waiting to be merged.

Best Regards!
